### ISSUE TITLE
Mistake in Exercise 3 key

### ISSUE THREAD

**Issue by kcampana** [seanchrismurphy/A-Psychologists-Guide-to-R#1]
At the end of Exercise 3 - Subsetting with Replacement - answers.R I think the very last line is incorrect.

For exercise 7, you ask participants to replace NA with 0.
The answer you have in there is: **missing_example[!is.na(missing_example)] <- 0**

I believe the correct answer is **missing_example[is.na(missing_example)] <- 0**

The inclusion of the exclamation point leads to a data set that is only zeros and NA, which is the opposite of what you asked for. I think. I'm new at this.

These materials are excellent, overall. Very glad I found them!

**Comment by seanchrismurphy** [comment]
Thanks for catching this - I've corrected the mistake.
